#ifndef H_PROCMAN_LSOF_1161179202
#define H_PROCMAN_LSOF_1161179202

#include <glib/gmacros.h>
#include "procman.h"

G_BEGIN_DECLS

enum ProcmanLsof {
	PROCMAN_LSOF_COL_PIXBUF,
	PROCMAN_LSOF_COL_PROCESS,
	PROCMAN_LSOF_COL_PID,
	PROCMAN_LSOF_COL_FILENAME,
	PROCMAN_LSOF_NCOLS
};

void procman_lsof(ProcData *data);

G_END_DECLS

#endif /* H_PROCMAN_LSOF_1161179202 */
